# Generated by Django 3.0.2 on 2020-01-25 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=50)),
                ('quiz_description', models.CharField(max_length=100)),
                ('quiz_difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=50)),
                ('question_text', models.CharField(max_length=100)),
                ('is_multi_answer', models.BooleanField(default=False)),
                ('quiz_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_title', models.CharField(max_length=50)),
                ('answer_text', models.CharField(max_length=100)),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('number_of_points', models.IntegerField(default=0)),
                ('question_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.Question')),
            ],
        ),
    ]
